### ISSUE TITLE
Questions About ResNet101 for CIFAR Experiments

### ISSUE THREAD

**Issue by jiamings** [google/mentornet#1]
I am curious about how the # of parameters are computed (https://arxiv.org/pdf/1712.05055.pdf). 

Seems like the code here uses some sort of WideResNet-101-10, but since WideResNet-28-10 has around 36.5M params, a network that is 101 layers would give almost 1.5B parameters right?

This is almost 2x larger than your reported numbers. Or did you use a smaller architecture in the paper?

**Comment by roadjiang** [comment]
The detailed model configuration is described in https://github.com/google/mentornet/blob/master/code/resnet_model.py

and you can use the following code to print the #model parameters:

      param_stats = tf.contrib.tfprof.model_analyzer.print_model_analysis(
      tf.get_default_graph(),
      tfprof_options=tf.contrib.tfprof.model_analyzer. TRAINABLE_VARS_PARAMS_STAT_OPTIONS)
      logging.info('total_params: %d\n', param_stats.total_parameters)
